flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
    path("<uuid:pk>/preview", views.PreviewView.as_view(), name="preview"),
]

onair/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from myuser.views import mapview

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("myuser.urls")),
    path("flights/", include("flights.urls")),
    path("pictures/", include("pictures.urls")),
    path("map/", mapview, name="map"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictures/urls.py
from django.urls import path

from . import views

app_name = "pictures"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
]

flights/models.py
import json
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Flight(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    embed_id = models.CharField(max_length=36)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="flights")
    name = models.CharField(max_length=100, null=False, blank=False)
    is_public = models.BooleanField(default=False)
    data_file = models.FileField(upload_to="flights/")
    description = models.CharField(max_length=500, blank=True)
    created = models.DateTimeField(default=timezone.now)
    departure = models.ForeignKey("Airport", on_delete=models.SET_NULL, related_name="departures", null=True)
    arrival = models.ForeignKey("Airport", on_delete=models.SET_NULL, related_name="arrivals", null=True)
    intended = models.ForeignKey("Airport", on_delete=models.SET_NULL, related_name="intended", null=True)
    start = models.DateTimeField(null=True)
    takeoff = models.DateTimeField(null=True)
    landing = models.DateTimeField(null=True)
    aircraft = models.ForeignKey("Aircraft", on_delete=models.SET_NULL, related_name="flights", null=True)
    aircraft_identifier = models.CharField(max_length=10, blank=True)

    class Meta:
        ordering = ["-start"]
        constraints = [models.UniqueConstraint(fields=["owner", "embed_id"], name="unique flight_owner")]

    def get_absolute_url(self):
        return reverse("flights:detail", args=[self.id])

    def save(self, reparse=False, creation=False, *args, **kwargs):
        if reparse:
            # Delete all waypoint if any
            self.waypoints.all().delete()
            # Parse the data file
            with self.data_file.open() as f:
                data = json.load(f)
                test = Flight.objects.filter(embed_id=data["Flight"]["Id"])
                if creation and test.exists():
                    return test.first()
                self.embed_id = data["Flight"]["Id"]
                # Some general data about the flight
                self.start = data["Flight"]["StartTime"]
                self.takeoff = data["Flight"]["AirborneTime"]
                self.landing = data["Flight"]["LandedTime"]
                # Try to get/create the depart/arrival airport
                self.departure = Airport.objects.update_or_create(
                    onair_id=data["Flight"]["DepartureAirportId"],
                    defaults={
                        "onair_id": data["Flight"]["DepartureAirport"]["Id"],
                        "ICAO": data["Flight"]["DepartureAirport"]["ICAO"],
                        "IATA": data["Flight"]["DepartureAirport"].get("IATA", None),
                        "name": data["Flight"]["DepartureAirport"]["Name"],
                        "state": data["Flight"]["DepartureAirport"].get("State", None),
                        "country_code": data["Flight"]["DepartureAirport"].get("CountryCode", None),
                        "country_name": data["Flight"]["DepartureAirport"].get("CountryName", None),
                        "city": data["Flight"]["DepartureAirport"].get("City", None),
                        "display_name": data["Flight"]["DepartureAirport"]["DisplayName"],
                        "lat": data["Flight"]["DepartureAirport"]["Latitude"],
                        "lon": data["Flight"]["DepartureAirport"]["Longitude"],
                        "alt": data["Flight"]["DepartureAirport"]["Elevation"],
                    },
                )[0]
                if data["Flight"]["ArrivalActualAirportId"]:
                    self.arrival = Airport.objects.update_or_create(
                        onair_id=data["Flight"]["ArrivalActualAirportId"],
                        defaults={
                            "onair_id": data["Flight"]["ArrivalActualAirport"]["Id"],
                            "ICAO": data["Flight"]["ArrivalActualAirport"]["ICAO"],
                            "IATA": data["Flight"]["ArrivalActualAirport"].get("IATA", None),
                            "name": data["Flight"]["ArrivalActualAirport"]["Name"],
                            "state": data["Flight"]["ArrivalActualAirport"].get("State", None),
                            "country_code": data["Flight"]["ArrivalActualAirport"].get("CountryCode", None),
                            "country_name": data["Flight"]["ArrivalActualAirport"].get("CountryName", None),
                            "city": data["Flight"]["ArrivalActualAirport"].get("City", None),
                            "display_name": data["Flight"]["ArrivalActualAirport"]["DisplayName"],
                            "lat": data["Flight"]["ArrivalActualAirport"]["Latitude"],
                            "lon": data["Flight"]["ArrivalActualAirport"]["Longitude"],
                            "alt": data["Flight"]["ArrivalActualAirport"]["Elevation"],
                        },
                    )[0]
                if data["Flight"]["ArrivalIntendedAirportId"]:
                    self.intended = Airport.objects.update_or_create(
                        onair_id=data["Flight"]["ArrivalIntendedAirportId"],
                        defaults={
                            "onair_id": data["Flight"]["ArrivalIntendedAirport"]["Id"],
                            "ICAO": data["Flight"]["ArrivalIntendedAirport"]["ICAO"],
                            "IATA": data["Flight"]["ArrivalIntendedAirport"].get("IATA", None),
                            "name": data["Flight"]["ArrivalIntendedAirport"]["Name"],
                            "state": data["Flight"]["ArrivalIntendedAirport"].get("State", None),
                            "country_code": data["Flight"]["ArrivalIntendedAirport"].get("CountryCode", None),
                            "country_name": data["Flight"]["ArrivalIntendedAirport"].get("CountryName", None),
                            "city": data["Flight"]["ArrivalIntendedAirport"].get("City", None),
                            "display_name": data["Flight"]["ArrivalIntendedAirport"]["DisplayName"],
                            "lat": data["Flight"]["ArrivalIntendedAirport"]["Latitude"],
                            "lon": data["Flight"]["ArrivalIntendedAirport"]["Longitude"],
                            "alt": data["Flight"]["ArrivalIntendedAirport"]["Elevation"],
                        },
                    )[0]
                self.aircraft_identifier = data["Flight"]["Aircraft"]["Identifier"]
                self.aircraft = Aircraft.objects.update_or_create(
                    name=data["SimAircraft"]["AircraftName"],
                    defaults={
                        "onair_id": data["Flight"]["Aircraft"]["Id"],
                        "name": data["SimAircraft"]["AircraftName"],
                    },
                )[0]
                super(Flight, self).save(*args, **kwargs)
                # Add all the waypoints
                for idx, wp in enumerate(data["StatPoints"]):
                    Waypoint(
                        flight=self,
                        index=idx,
                        lat=wp["Aircraft"]["Latitude"],
                        lon=wp["Aircraft"]["Longitude"],
                        alt=wp["Aircraft"]["Altitude"],
                    ).save()
                # super(Flight, self).save(*args, **kwargs)
                return self
        else:
            super(Flight, self).save(*args, **kwargs)
            return self

    def full_dico(self):
        out = {}
        out["flight"]: str(self.id)
        out["departure"] = [self.departure.lat, self.departure.lon]
        if self.arrival:
            out["arrival"] = [self.arrival.lat, self.arrival.lon]
        elif self.intended:
            out["arrival"] = [self.intended.lat, self.intended.lon]
        else:
            out["arrival"] = [0, 0]
        out["waypoints"] = [[wp.lat, wp.lon] for wp in self.waypoints.all()]
        return out


class Waypoint(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, related_name="waypoints")
    index = models.PositiveIntegerField()
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    alt = models.DecimalField(max_digits=7, decimal_places=2)
    # Storing speed and whatnot?
    # speed = Positive Integer
    # compas = Positive Integer
    # Drawing a virtual horizon somewhere?
    # Pitch ? = Integer
    # Bank ? = Integer

    class Meta:
        ordering = ["flight", "index"]


class Airport(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    onair_id = models.CharField(max_length=36, unique=True, null=True, blank=True)
    ICAO = models.CharField(max_length=4)  # Validator only capital letter
    IATA = models.CharField(max_length=3, null=True)  # Validator only capital letter
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=100, null=True)
    country_code = models.CharField(max_length=2, null=True)
    country_name = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    display_name = models.CharField(max_length=200)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    alt = models.DecimalField(max_digits=6, decimal_places=2)


class Aircraft(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    onair_id = models.CharField(max_length=36, null=True, blank=True)
    name = models.CharField(max_length=100, unique=True, null=False, blank=False)

flights/views.py
import urllib.request

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import (
    Http404,
    HttpResponseForbidden,
    HttpResponseRedirect,
    JsonResponse,
)
from django.urls import reverse_lazy
from django.views import generic

from .models import Flight


class IndexView(LoginRequiredMixin, generic.ListView):
    paginate_by = 10
    template_name = "flights/index.html"

    def get_queryset(self):
        return Flight.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["ALLOW_PREVIEW"] = settings.ALLOW_PREVIEW
        return context


class DetailView(generic.DetailView):
    model = Flight
    template_name = "flights/detail.html"

    def get(self, request, *args, **kwargs):
        response = super(DetailView, self).get(request)
        if not (self.object.is_public or (request.user == self.object.owner)):
            raise Http404()
        is_ajax = request.headers.get("Accept") == "application/json"
        if is_ajax:
            response = JsonResponse(self.object.full_dico())
        return response


class PreviewView(generic.DetailView):
    model = Flight
    template_name = "flights/preview.html"

    def get(self, request, *args, **kwargs):
        if request.META["HTTP_X_REAL_IP"] in settings.PREVIEW_ALLOWED_IPS:
            return super(PreviewView, self).get(request)
        return HttpResponseForbidden("<h1>Forbidden</h1>")


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Flight
    fields = ["name", "description", "is_public"]
    template_name = "flights/create_update.html"

    def get_queryset(self):
        queryset = super(UpdateView, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Flight
    template_name = "flights/detail.html"
    success_url = reverse_lazy("flights:list")

    def get_queryset(self):
        queryset = super(DeleteView, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class CreateView(LoginRequiredMixin, generic.CreateView):
    model = Flight
    fields = ["name", "description", "data_file", "is_public"]
    template_name = "flights/create_update.html"

    @transaction.atomic
    def form_valid(self, form):
        # response = super(CreateView, self).form_valid(form)
        # # do something with self.object
        # return response
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj = obj.save(reparse=True, creation=True)
        # Trigger the thumbnail generation process
        if settings.ALLOW_PREVIEW:
            urllib.request.urlopen(settings.PREVIEWER_URL.format(obj.pk))
        return HttpResponseRedirect(obj.get_absolute_url())

templates/flights/create.html
{% extends 'base.html' %}

{% block content %}
<div class="login-box">
  <div class="card">
    <header class="card-header has-background-light">
      <p class="card-header-title">Add a flight</p>
    </header>
    <div class="card-content">
      <div class="content">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {% if form.non_field_errors %}
          <p class="help is-danger">{{ form.non_field_errors }}</p>
          {% endif %}

          <div class="field">
            <label class="label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <div class="control">
              <input class="input" type="text" name="{{ form.name.html_name  }}" id="{{ form.name.id_for_label }}" placeholder="Name of this flight" value="{{ form.name.value|default_if_none:"" }}">
            </div>
            {% for error in form.name.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="field">
            <label class="label" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            <div class="control">
              <textarea class="textarea" name="{{ form.description.html_name  }}" id="{{ form.description.id_for_label }}" placeholder="Description">{{ form.description.value|default_if_none:"" }}</textarea>
            </div>
            {% for error in form.description.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="file has-name">
            <label class="file-label">
              <input class="file-input" type="file" name="{{ form.data_file.html_name  }}" id="{{ form.data_file.id_for_label }}">
              <span class="file-cta">
                <span class="file-icon">
                  <i class="mdi mdi-upload"></i>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
              <span class="file-name">
              </span>
            </label>
          </div>

          <div class="control has-text-right">
            <button class="button is-link" type="submit">
              <span class="icon mr-1">
                <i class="mdi mdi-plus"></i>
              </span>
              Add
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer_js %}
<script>
const fileInput = document.querySelector('input[type=file]')
fileInput.onchange = () => {
  if (fileInput.files.length > 0) {
    const fileName = document.querySelector('.file-name')
    fileName.textContent = fileInput.files[0].name
  }
}


document.querySelector('button[type=submit]').addEventListener('click', function(event) {
  event.target.classList.add("is-loading")
});

</script>
{% endblock %}

templates/flights/create_update.html
{% extends 'base.html' %}

{% block content %}
<div class="login-box">
  <div class="card">
    <header class="card-header has-background-light">
      <p class="card-header-title">{% if not object %}Add{% else %}Edit{% endif %} a flight</p>
    </header>
    <div class="card-content">
      <div class="content">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {% if form.non_field_errors %}
          <p class="help is-danger">{{ form.non_field_errors }}</p>
          {% endif %}

          <div class="field">
            <label class="label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <div class="control">
              <input class="input" type="text" name="{{ form.name.html_name  }}" id="{{ form.name.id_for_label }}" placeholder="Name of this flight" value="{{ form.name.value|default_if_none:"" }}">
            </div>
            {% for error in form.name.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="field">
            <label class="label" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            <div class="control">
              <textarea class="textarea" name="{{ form.description.html_name  }}" id="{{ form.description.id_for_label }}" placeholder="Description">{{ form.description.value|default_if_none:"" }}</textarea>
            </div>
            {% for error in form.description.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          {% if not object %}
          <div class="file has-name">
            <label class="file-label">
              <input class="file-input" type="file" name="{{ form.data_file.html_name  }}" id="{{ form.data_file.id_for_label }}">
              <span class="file-cta">
                <span class="file-icon">
                  <i class="mdi mdi-upload"></i>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
              <span class="file-name">
              </span>
            </label>
          </div>
          <div class="help">OnAir flights are in <code>My Documents/OnAir Company/flights</code></div>
          {% endif %}

          <div class="field">
            <label class="label" for="{{ form.is_public.id_for_label }}">{{ form.is_public.label }}</label>
            <div class="control">
              <input type="checkbox" name="{{ form.is_public.html_name  }}" id="{{ form.is_public.id_for_label }}" {% if form.is_public.value %}checked{% endif %} />
              Mark this flight as public
            </div>
            {% for error in form.is_public.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
            <div class="help">A public flight can be accessed to anyone with its URL, without loggin in or being its owner. Useful if you want to share a flight with some friends.</div>
          </div>

          <div class="control has-text-right">
          {% if not object %}
            <button class="button is-link" type="submit">
              <span class="icon mr-1">
                <i class="mdi mdi-plus"></i>
              </span>
              Add
            </button>
          {% else %}
            <button class="button is-link" type="submit">
              Update
            </button>
          {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% include 'tipeee.part.html' %}
{% endblock %}

{% block footer_js %}
<script>
const fileInput = document.querySelector('input[type=file]')
fileInput.onchange = () => {
  if (fileInput.files.length > 0) {
    const fileName = document.querySelector('.file-name')
    fileName.textContent = fileInput.files[0].name
  }
}


document.querySelector('button[type=submit]').addEventListener('click', function(event) {
  event.target.classList.add("is-loading")
});

</script>
{% endblock %}

templates/flights/detail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_og %}
<meta property="og:title" content="{{ object.name }}">
<meta property="og:author" content="{{ object.owner.username }}">
<!-- TODO change those hardcoded url!! -->
<meta property="og:url" content="https://travelbook.eskimon.fr{{ object.get_absolute_url }}">
<meta property="og:image" content="https://png.pimpyour.stream/i/flights/{{ object.pk }}.png">
{% if object.description %}<meta property="og:description" content="{{ object.description }}">{% endif %}

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="travelbook.eskimon.fr">
<!--<meta name="twitter:creator" content="{{ object.owner.username }}">-->
<meta name="twitter:title" content="{{ object.name }}">
<meta name="twitter:image" content="https://png.pimpyour.stream/i/flights/{{ object.pk }}.png">
{% if object.description %}<meta name="twitter:description" content="{{ object.description }}">{% endif %}
{% endblock %}

{% block content %}

<div class="flight-box">
  <div id="map"></div>

  <div class="card">
    <header class="card-header has-background-light">
      <p class="card-header-title is-clickable">{{ object.name }}</p>
    </header>
    <div class="card-content">
      <div class="content">
        {% if object.description %}
        <p class="subtitle is-6"><em>{{ object.description }}</em></p>
        {% endif %}

        <p class="airport from is-clickable mb-0"><strong>From:</strong> {{ object.departure.display_name }}</p>
        {% if object.arrival %}
        <p class="airport to is-clickable"><strong>To:</strong> {{ object.arrival.display_name }}</p>
        {% else %}
        <p class="airport mb-0"><strong>To:</strong> None</p>
        <p class="airport to is-clickable">(Intended: {{ object.intended.display_name }})</p>
        {% endif %}
        <p class="mb-0"><strong>Started at:</strong> {{ object.start }}</p>
        <p class="mb-0"><strong>Airborn at:</strong> {{ object.takeoff }}</p>
        <p><strong>Landing at:</strong> {{ object.landing }}</p>
        {% if object.aircraft %}
        <p><strong>Aircraft:</strong> {{ object.aircraft.name }} {% if object.aircraft_identifier %}({{ object.aircraft_identifier }}){% endif %}</p>
        {% endif %}
        {% if request.user == object.owner %}
        <p class="is-flex is-justify-content-space-between mt-5">
          <a class="button is-link" title="Add a picture to this flight" href="{% url 'pictures:create' %}?flight={{ flight.id }}"><i class="mdi mdi-image-plus"></i></a>
          <a class="button is-info" title="Edit this flight" href="{% url 'flights:update' object.pk %}"><i class="mdi mdi-square-edit-outline"></i></a>
          <button class="button is-danger modal-opener" data-target="delete-flight-modal"><i class="mdi mdi-delete"></i></button>
        </p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% if request.user == object.owner %}
<div class="modal" id="delete-flight-modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Are you sure?</p>
    </header>
    <section class="modal-card-body">
      Are you sure you want to delete this flight?
    </section>
    <footer class="modal-card-foot is-flex is-justify-content-flex-end">
      <form method="post" action="{% url 'flights:delete' object.pk %}">
        {% csrf_token %}
        <input type="submit" value="Yes, delete that!" class="button is-danger" >
      </form>
    </footer>
  </div>
</div>
{% endif %}

{% comment %} TODO: on click on departure/arrival <p> tag, center map on airport {% endcomment %}
{% include 'tipeee.part.html' %}
{% endblock %}

{% block footer_js %}
<script>
var map = L.map('map').setView([47.4771198,-0.5972396], 6);

let map_choice = {% if request.user.profile %}{{ request.user.profile.maps }}{% else %}0{% endif %}
if(map_choice == 1) {
  // Topo
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
  }).addTo(map);
} else if(map_choice == 2) {
  // Imagery
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
  }).addTo(map);
} else {
  // Standard
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
}




let dep = [{{ object.departure.lat }}, {{ object.departure.lon }}]
{% if object.arrival %}
let arr = [{{ object.arrival.lat }}, {{ object.arrival.lon }}]
{% elif object.intended %}
let arr = [{{ object.intended.lat }}, {{ object.intended.lon }}]
{% else %}
let arr = [0, 0]
{% endif %}
let pts = [
{% for wp in object.waypoints.all %}
  [{{ wp.lat }}, {{ wp.lon }}],
{% endfor %}
]

let polyline = drawFlight(dep, arr, pts, map, {% if request.user.profile %}{{ request.user.profile.icons }}{% else %}1{% endif %})

map.fitBounds(polyline.polyline.getBounds())

document.querySelector('header').addEventListener('click', function(event) {
  map.fitBounds(polyline.polyline.getBounds())
});

document.querySelector('.airport.from').addEventListener('click', function(event) {
  map.panTo(dep, {animate: true});
});

document.querySelector('.airport.to').addEventListener('click', function(event) {
  map.panTo(arr, {animate: true});
});


{% for picture in flight.pictures.all %}
{% if picture.is_public or request.user == picture.owner %}
drawPicture([{{ picture.lat }}, {{ picture.lon }}], "{{ picture.name }}", "{{ picture.description }}", "{{ picture.data_file.url }}", map, {{ request.user.icons }})
{% endif %}
{% endfor %}

</script>
{% endblock %}

templates/flights/index.html
{% extends 'base.html' %}

{% block content %}
<div class="has-text-centered mt-4">
  <a class="button is-link" href="{% url 'flights:create' %}" title="Add a new picture"><i class="mdi mdi-plus mr-2"></i> Add a flight</a>
</div>

<div class="fligths-list columns py-5 is-multiline has-text-centered is-justify-content-center">
  {% for flight in object_list %}
  <a class="card m-2 column is-one-quarter is-one-fifth-fullhd" href="{% url 'flights:detail' flight.pk %}">
    <div class="card-image">
      <figure class="image is-4by3">
        <img src="{% if ALLOW_PREVIEW %} https://png.pimpyour.stream/i/flights/{{ flight.pk }}.png {% else %} https://via.placeholder.com/640x480 {% endif %}">
      </figure>
    </div>
    <div class="card-content">
      <div class="content">
        <p class="title is-4">{{ flight.name }}</p>
        <p class="subtitle is-6">{{ flight.description }}</p>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% if page_obj.has_previous or page_obj.has_next  %}
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
  <ul class="pagination-list">
    {% for num in page_obj.paginator.page_range %}
    <li><a class="is-justify-content-center pagination-link {% if num == page_obj.number %}is-current{% endif %}" aria-label="Goto page {{ num }}" href="{% if num == page_obj.number %}#{% else %}?page={{ num }}{% endif %}">{{ num }}</a></li>
    {% endfor %}
  </ul>
</nav>
{% endif %}

{% include 'tipeee.part.html' %}
{% endblock %}

templates/flights/preview.html
{% load static %}
{% load render_bundle from webpack_loader %}

<!doctype html>

<html lang="en" style="overflow: hidden;">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" href="/favicon.ico">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  {% render_bundle 'global' 'css' %}
  {% render_bundle 'global' 'js' %}
</head>

<body>
  <div class="preview-flight">
    <div id="map"></div>
  </div>

  <script>
  var map = L.map('map', {zoomControl: false, attributionControl: false})

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {}).addTo(map)

  let dep = [{{ object.departure.lat }}, {{ object.departure.lon }}]
  {% if object.arrival %}
  let arr = [{{ object.arrival.lat }}, {{ object.arrival.lon }}]
  {% elif object.intended %}
  let arr = [{{ object.intended.lat }}, {{ object.intended.lon }}]
  {% else %}
  let arr = [0, 0]
  {% endif %}
  let pts = [
  {% for wp in object.waypoints.all %}
    [{{ wp.lat }}, {{ wp.lon }}],
  {% endfor %}
  ]

  let polyline = drawFlight(dep, arr, pts, map)

  map.fitBounds(polyline.polyline.getBounds())
  </script>
</body>

</html>