flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
    path("<uuid:pk>/preview", views.PreviewView.as_view(), name="preview"),
]

onair/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from myuser.views import mapview

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("myuser.urls")),
    path("flights/", include("flights.urls")),
    path("pictures/", include("pictures.urls")),
    path("map/", mapview, name="map"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictures/urls.py
from django.urls import path

from . import views

app_name = "pictures"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
]

pictures/models.py
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

from flights.models import Flight


class Picture(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="pictures")
    name = models.CharField(max_length=100, null=False, blank=False)
    is_public = models.BooleanField(default=False)
    data_file = models.ImageField(upload_to="pictures/")
    description = models.CharField(max_length=500, blank=True)
    created = models.DateTimeField(default=timezone.now)
    flight = models.ForeignKey(Flight, on_delete=models.SET_NULL, related_name="pictures", null=True, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, blank=False, null=False)
    lon = models.DecimalField(max_digits=9, decimal_places=6, blank=False, null=False)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("pictures:detail", args=[self.id])

pictures/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views import generic

from flights.models import Flight

from .models import Picture


class IndexView(LoginRequiredMixin, generic.ListView):
    paginate_by = 10
    template_name = "pictures/index.html"

    def get_queryset(self):
        flights = self.request.GET.getlist("flights", [])
        qs = Picture.objects.filter(owner=self.request.user)
        if flights:
            qs = qs.filter(flight__in=flights)
        return qs


class DetailView(generic.DetailView):
    model = Picture
    template_name = "pictures/detail.html"

    def get(self, request, *args, **kwargs):
        response = super(DetailView, self).get(request)
        if self.object.is_public or (request.user == self.object.owner):
            return response
        raise Http404()


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Picture
    fields = ["name", "description", "flight", "lat", "lon", "is_public"]
    template_name = "pictures/create_update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["flights"] = Flight.objects.filter(owner=self.request.user).all()
        return context

    def get_queryset(self):
        queryset = super(UpdateView, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Picture
    template_name = "pictures/detail.html"
    success_url = reverse_lazy("pictures:list")

    def get_queryset(self):
        queryset = super(DeleteView, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class CreateView(LoginRequiredMixin, generic.CreateView):
    model = Picture
    fields = ["name", "description", "data_file", "flight", "lat", "lon", "is_public"]
    template_name = "pictures/create_update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["flights"] = Flight.objects.filter(owner=self.request.user).all()
        return context

    def get_initial(self):
        initial = super(CreateView, self).get_initial()
        initial = initial.copy()
        flight_id = self.request.GET.get("flight", None)
        if flight_id:
            flight = Flight.objects.get(id=flight_id)
            if flight:
                initial["flight"] = flight.id
        return initial

    @transaction.atomic
    def form_valid(self, form):
        # TODO check that flight belong to user
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return HttpResponseRedirect(obj.get_absolute_url())

    def post(self, request, *args, **kwargs):
        next_page = super(CreateView, self).post(request, *args, **kwargs)
        if "_another" in request.POST:
            url = f'{reverse("pictures:create")}'
            # Keep the flight if provided
            flight_id = request.POST["flight"]
            if flight_id:
                flight = {"flight": flight_id}
                url += f"?{urlencode(flight)}"
            next_page = HttpResponseRedirect(url)
        return next_page

templates/pictures/create_update.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<div class="picture-box">
  <div id="map"></div>
  <div class="card">
    <header class="card-header has-background-light">
      <p class="card-header-title">{% if not object %}Add{% else %}Edit{% endif %} a picture</p>
    </header>
    <div class="card-content">
      <div class="content">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {% if form.non_field_errors %}
          <p class="help is-danger">{{ form.non_field_errors }}</p>
          {% endif %}

          <div class="field">
            <label class="label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <div class="control">
              <input class="input" type="text" name="{{ form.name.html_name  }}" id="{{ form.name.id_for_label }}" placeholder="Name of this picture" value="{{ form.name.value|default_if_none:"" }}">
            </div>
            {% for error in form.name.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="field">
            <label class="label" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            <div class="control">
              <textarea class="textarea" rows="2" name="{{ form.description.html_name  }}" id="{{ form.description.id_for_label }}" placeholder="Description">{{ form.description.value|default_if_none:"" }}</textarea>
            </div>
            {% for error in form.description.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          {% if not object %}
          <div class="field">
            <div class="file has-name">
              <label class="file-label">
                <input class="file-input" type="file" name="{{ form.data_file.html_name  }}" id="{{ form.data_file.id_for_label }}" accept="image/*">
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="mdi mdi-upload"></i>
                  </span>
                  <span class="file-label">
                    Choose a file…
                  </span>
                </span>
                <span class="file-name">
                </span>
              </label>
            </div>
          </div>
          {% endif %}

          <div class="field">
            <label class="label" for="{{ form.flight.id_for_label }}">{{ form.flight.label }}</label>
            <div class="control">
              <div class="select">
                <select name="{{ form.flight.html_name  }}" id="{{ form.flight.id_for_label }}">
                <option value="" {% if not form.flight.value %}selected{% endif %}>None</option>
                {% for flight in flights %}
                  <option value="{{ flight.id }}" {% if flight.id == form.flight.value %}selected{% endif %}>{{ flight.name }}</option>
                {% endfor %}
                </select>
              </div>
            </div>
            <div class="help">Attach this picture to a flight</div>
            {% for error in form.flight.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="field">
            <div class="field-body">
              <div class="field">
                <label class="label" for="{{ form.lat.id_for_label }}">{{ form.lat.label }}</label>
                <div class="control">
                  <input class="input" type="number" step="0.000001" name="{{ form.lat.html_name  }}" id="{{ form.lat.id_for_label }}" placeholder="Latitude" value="{{ form.lat.value|default_if_none:"0.0000" }}">
                </div>
                {% for error in form.lat.errors %}
                <p class="help is-danger">{{ error }}</p>
                {% endfor %}
              </div>

              <div class="field">
                <label class="label" for="{{ form.lon.id_for_label }}">{{ form.lon.label }}</label>
                <div class="control">
                  <input class="input" type="number" step="0.000001" name="{{ form.lon.html_name  }}" id="{{ form.lon.id_for_label }}" placeholder="Longitude" value="{{ form.lon.value|default_if_none:"0.0000" }}">
                </div>
                {% for error in form.lon.errors %}
                <p class="help is-danger">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
          </div>

          <div class="field">
            <label class="label" for="{{ form.is_public.id_for_label }}">{{ form.is_public.label }}</label>
            <div class="control">
              <input type="checkbox" name="{{ form.is_public.html_name  }}" id="{{ form.is_public.id_for_label }}" {% if form.is_public.value %}checked{% endif %} />
              <label for="{{ form.is_public.id_for_label }}">Mark this picture as public</label>
            </div>
            {% for error in form.is_public.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
            <div class="help">A public picture can be accessed to anyone with its URL, without loggin in or being its owner. Useful if you want to share a picture with some friends.</div>
          </div>

          {% if not object %}
            <div class="control is-flex is-justify-content-space-between">
              <button class="button is-link" type="submit" name="_another">
                <span class="icon mr-1">
                  <i class="mdi mdi-plus"></i>
                </span>
                Save and add another
              </button>
              <button class="button is-link" type="submit" name="_save">
                <span class="icon mr-1">
                  <i class="mdi mdi-plus"></i>
                </span>
                Save
              </button>
            <div>
            {% else %}
            <div class="control has-text-right">
              <button class="button is-link" type="submit" name="_update">
                Update
              </button>
            </div>
          {% endif %}
        </form>

        {% if object %}
          <img class="mt-3 lb-source" src="{{ object.data_file.url }}">
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% include 'lightbox.part.html' %}
{% include 'tipeee.part.html' %}

{% endblock %}


{% block footer_js %}
<script>
const fileInput = document.querySelector('input[type=file]')
if(fileInput) {
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('.file-name')
      fileName.textContent = fileInput.files[0].name
    }
  }
}

document.querySelector('button[type=submit]').addEventListener('click', function(event) {
  event.target.classList.add("is-loading")
});


// Setup map
var map = L.map('map').setView([47.4771198,-0.5972396], 6);

let map_choice = {{ request.user.profile.maps }}
if(map_choice == 1) {
  // Topo
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
  }).addTo(map);
} else if(map_choice == 2) {
  // Imagery
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
  }).addTo(map);
} else {
  // Standard
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
}


// Draw flight if any
var polyline = {}
var flights = {}
{% for flight in flights.all %}
  flights['{{ flight.id }}'] = {
    dep: [{{ flight.departure.lat }}, {{ flight.departure.lon }}],
    arr: {% if flight.arrival %}[{{ flight.arrival.lat }}, {{ flight.arrival.lon }}]{% else %}[{{ flight.intended.lat }}, {{ flight.intended.lon }}]{% endif %},
    pts: [{% for wp in flight.waypoints.all %}[{{ wp.lat }}, {{ wp.lon }}],{% endfor %}],
  }
{% endfor %}

{% if object.flight %}
polyline = drawFlight(flights["{{ object.flight.id }}"].dep, flights["{{ object.flight.id }}"].arr, flights["{{ object.flight.id }}"].pts, map, {{ request.user.profile.icons }})
{% comment %} map.fitBounds(polyline.polyline.getBounds()) {% endcomment %}
{% elif form.flight.value %}
polyline = drawFlight(flights["{{ form.flight.value }}"].dep, flights["{{ form.flight.value }}"].arr, flights["{{ form.flight.value }}"].pts, map, {{ request.user.profile.icons }})
map.fitBounds(polyline.polyline.getBounds())
{% endif %}

// Redraw flight when selection change
document.getElementById("id_flight").addEventListener('change', function(event) {
  if(polyline.polyline) {
    polyline.dep_mark.remove()
    polyline.arr_mark.remove()
    polyline.polyline.remove()
  }
  let id = event.target.value
  polyline = drawFlight(flights[id].dep, flights[id].arr, flights[id].pts, map, {{ request.user.profile.icons }})
  map.fitBounds(polyline.polyline.getBounds())
  // Move marker somewhere on the flight, on any waypoint
  let randIdx = Math.floor((flights[id].pts.length / 3) + ((Math.random() * flights[id].pts.length) / 2))
  let point = flights[id].pts[randIdx]
  marker.setLatLng(point)
  document.getElementById("id_lat").value = point[0].toFixed(6)
  document.getElementById("id_lon").value = point[1].toFixed(6)
});

// Marker for the pic
var marker = L.marker([{{ form.lat.value|default_if_none:0.000 }}, {{ form.lon.value|default_if_none:0.000 }}], {draggable: true, autoPan: true}).addTo(map)
{% if form.flight.value and not object %}
// The object doesn't exist but a flight is provided, move towards it with random coords
let flightId = "{{ form.flight.value }}"
let randIdx = Math.floor((flights[flightId].pts.length / 3) + ((Math.random() * flights[flightId].pts.length) / 2))
let point = flights[flightId].pts[randIdx]
marker.setLatLng(point)
document.getElementById("id_lat").value = point[0].toFixed(6)
document.getElementById("id_lon").value = point[1].toFixed(6)
{% endif %}
map.panTo(marker.getLatLng())

// move marker according to the form input change
document.getElementById("id_lat").addEventListener('change', function(event) {
  let latlng = marker.getLatLng()
  latlng.lat = event.target.value
  marker.setLatLng(latlng)
  map.panTo(marker.getLatLng())
});
document.getElementById("id_lon").addEventListener('change', function(event) {
  let latlng = marker.getLatLng()
  latlng.lng = event.target.value
  marker.setLatLng(latlng)
  map.panTo(marker.getLatLng())
});

// Move marker on drag
marker.on('moveend', (event) => {
  let latlng = marker.getLatLng()
  document.getElementById("id_lat").value = latlng.lat.toFixed(6)
  document.getElementById("id_lon").value = latlng.lng.toFixed(6)
});

// Move marker on map click
map.on('click', (event) => {
  let latlng = event.latlng
  marker.setLatLng(latlng)
  document.getElementById("id_lat").value = latlng.lat.toFixed(6)
  document.getElementById("id_lon").value = latlng.lng.toFixed(6)
});

</script>
{% endblock %}

templates/pictures/detail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_og %}
<meta property="og:title" content="{{ object.name }}">
<meta property="og:author" content="{{ object.owner.username }}">
<!-- TODO change those hardcoded url!! -->
<meta property="og:url" content="https://travelbook.eskimon.fr{{ object.get_absolute_url }}">
<meta property="og:image" content="https://travelbook.eskimon.fr{{ object.data_file.url }}">
{% if object.description %}<meta property="og:description" content="{{ object.description }}">{% endif %}

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="travelbook.eskimon.fr">
<!--<meta name="twitter:creator" content="{{ object.owner.username }}">-->
<meta name="twitter:title" content="{{ object.name }}">
<meta name="twitter:image" content="https://travelbook.eskimon.fr{{ object.data_file.url }}">
{% if object.description %}<meta name="twitter:description" content="{{ object.description }}">{% endif %}
{% endblock %}

{% block content %}
<div class="picture-box">
  <div id="map"></div>
  <div class="card">
    <header class="card-header has-background-light">
      <p class="card-header-title is-clickable">{{ object.name }}</p>
    </header>
    <div class="card-content">
      <div class="content">
        {% if object.description %}
        <p class="subtitle is-6"><em>{{ object.description }}</em></p>
        {% endif %}

        <p class="mb-0"><strong>Coordinates:</strong> {{ object.lat }} - {{ object.lon }}</p>
        {% if object.flight %}
        {% if object.flight.is_public or request.user == object.owner %}
        <p class="mb-0"><em>Attached to flight <strong><a href="{% url 'flights:detail' object.flight.pk %}" title="{{ object.flight.description }}">{{ object.flight.name }}</a></strong></em></p>
        {% endif %}
        {% endif %}

        <img class="mt-2 lb-source" src="{{ object.data_file.url }}" data-name="{{ object.name }}" data-description="{{ object.description }}">
        {% if request.user == object.owner %}
        <p class="is-flex is-justify-content-space-between mt-5">
          <a class="button is-info" title="Edit this picture" href="{% url 'pictures:update' object.pk %}"><i class="mdi mdi-square-edit-outline"></i></a>
          <button class="button is-danger modal-opener" data-target="delete-pic-modal"><i class="mdi mdi-delete"></i></button>
        </p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% if request.user == object.owner %}
<div class="modal" id="delete-pic-modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Are you sure?</p>
    </header>
    <section class="modal-card-body">
      Are you sure you want to delete this picture?
    </section>
    <footer class="modal-card-foot is-flex is-justify-content-flex-end">
      <form method="post" action="{% url 'pictures:delete' object.pk %}">
        {% csrf_token %}
        <input type="submit" value="Yes, delete that!" class="button is-danger" >
      </form>
    </footer>
  </div>
</div>
{% endif %}

{% include 'lightbox.part.html' %}
{% include 'tipeee.part.html' %}

{% endblock %}

{% block footer_js %}
<script>
var map = L.map('map').setView([47.4771198,-0.5972396], 6);

let map_choice = {% if request.user.profile %}{{ request.user.profile.maps }}{% else %}0{% endif %}
if(map_choice == 1) {
  // Topo
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
  }).addTo(map);
} else if(map_choice == 2) {
  // Imagery
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
  }).addTo(map);
} else {
  // Standard
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
}



{% if object.flight %}
let dep = [{{ object.flight.departure.lat }}, {{ object.flight.departure.lon }}]
let arr = {% if object.flight.arrival %}[{{ object.flight.arrival.lat }}, {{ object.flight.arrival.lon }}]{% else %}[{{ object.flight.intended.lat }}, {{ object.flight.intended.lon }}]{% endif %}
let pts = [
{% for wp in object.flight.waypoints.all %}
  [{{ wp.lat }}, {{ wp.lon }}],
{% endfor %}
]

let polyline = drawFlight(dep, arr, pts, map, {% if request.user.profile %}{{ request.user.profile.icons }}{% else %}1{% endif %})
{% comment %} map.fitBounds(polyline.polyline.getBounds()) {% endcomment %}
{% endif %}

let coords = [{{ object.lat }}, {{ object.lon }}]
L.marker(coords).addTo(map)

map.panTo(coords)


document.querySelector('header').addEventListener('click', function(event) {
  map.panTo(coords, {animate: true});
});

</script>
{% endblock %}

templates/pictures/index.html
{% extends 'base.html' %}
{% load get_item %}


{% block content %}
<div class="is-flex is-justify-content-center is-align-items-center mt-4">
  <a class="button is-link mr-6" href="{% url 'pictures:create' %}" title="Add a new picture"><i class="mdi mdi-plus mr-2"></i> Add a picture</a>
  <form class="ml-6 is-flex is-align-items-center" action="#" method="GET">
    <label class="mr-2" for="flights">Show only picture for flight(s)</label>
    <div class="select is-multiple">
      <select id="flights" name="flights" multiple size="4">
        {% for flight in user.flights.all %}
          <option value="{{ flight.id }}" {% get_selected_item request.GET "flights" flight.id %}>{{ flight.name }}</option>
        {% endfor %}
      </select>
    </div>
    <button type="submit" class="ml-2"><i class="mdi mdi-image-filter-none mr-2"></i>Filter</button>
  </form>
</div>

<div class="pictures-list columns py-5 is-multiline has-text-centered is-justify-content-center">
  {% for picture in object_list %}
  <a class="card m-2 column is-one-quarter is-one-fifth-fullhd" href="{% url 'pictures:detail' picture.pk %}">
    <div class="card-image">
      <figure class="image">
        <img src="{{ picture.data_file.url }}">
      </figure>
    </div>
    <div class="card-content">
      <div class="content">
        <p class="title is-4">{{ picture.name }}</p>
        <p class="subtitle is-6">{{ picture.description }}</p>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% if page_obj.has_previous or page_obj.has_next  %}
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
  <ul class="pagination-list">
    {% for num in page_obj.paginator.page_range %}
      <li>
        <a class="is-justify-content-center pagination-link {% if num == page_obj.number %}is-current{% endif %}" aria-label="Goto page {{ num }}" href="?{% if num == page_obj.number %}{% else %}&page={{ num }}{% endif %}&{% encode_flights_item request.GET %}">{{ num }}</a>
      </li>
    {% endfor %}
  </ul>
</nav>
{% endif %}

{% include 'tipeee.part.html' %}

{% endblock %}