flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
    path("<uuid:pk>/preview", views.PreviewView.as_view(), name="preview"),
]

myuser/urls.py
from django.urls import path

from . import views

app_name = "myuser"


urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("<uuid:pk>", views.UpdateView.as_view(), name="update"),
]

onair/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from myuser.views import mapview

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("myuser.urls")),
    path("flights/", include("flights.urls")),
    path("pictures/", include("pictures.urls")),
    path("map/", mapview, name="map"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictures/urls.py
from django.urls import path

from . import views

app_name = "pictures"

urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("create", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>", views.DetailView.as_view(), name="detail"),
    path("<uuid:pk>/update", views.UpdateView.as_view(), name="update"),
    path("<uuid:pk>/delete", views.DeleteView.as_view(), name="delete"),
]

templates/base.html
{% load static %}
{% load active_tag %}
{% load render_bundle from webpack_loader %}

<!doctype html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="{% block description %}{% endblock %}">
  <meta name="author" content="{% block author %}{% endblock %}">

  <meta property="og:site_name" content="travelbook.eskimon.fr">
  <meta property="og:type" content="website">
  {% block extra_og %}{% endblock %}

  <link rel="icon" href="/favicon.ico">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <link rel="stylesheet" href="//cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">

  {% render_bundle 'global' 'css' %}
  {% render_bundle 'global' 'js' %}

  {% block head_css %}{% endblock %}
  {% block head_js %}{% endblock %}
</head>

<body>
  <!-- The navbar -->
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="{% static 'img/logo.png' %}" width="112" height="28">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      {% if user.is_authenticated %}
      <div class="navbar-start">
        <a class="navbar-item is-tab {% active '^/map/' %}" href="{% url 'map' %}">
          Map
        </a>

        <a class="navbar-item is-tab {% active '^/flights/' %}" href="{% url 'flights:list' %}">
          Flights
        </a>

        <a class="navbar-item is-tab {% active '^/pictures/' %}" href="{% url 'pictures:list' %}">
          Pictures
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            {{ request.user.username }}
          </a>

          <div class="navbar-dropdown ">
            <a class="navbar-item" href="{% url 'myuser:update' request.user.profile.pk %}">
              Settings
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item" href="{% url 'myuser:logout' %}">
              Logout
            </a>
          </div>
        </div>
      </div>
      {% else %}
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary" href="{% url 'myuser:signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'myuser:login' %}">
              Log in
            </a>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </nav>

  {% include 'messages.part.html' %}

  {% block content %}{% endblock %}

  {% block footer_js %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
{% endblock %}

templates/lightbox.part.html
<div class="lb-wrapper is-clickable">
  <h1 class="lb-name title"></h1>
  <img class="lb-img" src="" alt="">
  <h2 class="lb-description subtitle mt-3"></h2>
</div>

templates/map.html
{% extends 'base.html' %}

{% block content %}
<div class="detail-flight">
  <div id="map"></div>

  <div class="infos">
    <p class="mb-3">
      <label class="checkbox">
        <input type="checkbox" id="pictures-toggle" checked>
        Show/hide pictures
      </label>
    </p>
    <ul class="flight-list">
      {% for flight in flights.all %}
        <li id="flight-{{ flight.id }}" class="loading" data-flightid="{{ flight.id }}" title="{{ flight.description }} ({{ flight.departure.display_name }} - {% if flight.arrival %}{{ flight.arrival.display_name }}{% else %}{{ flight.intended.display_name }}{% endif %})">
          <span class="color-box" style="background-color: hsl({% widthratio forloop.counter0 1 color_step %}, 100%, 50%)"></span>
          <span class="flight-name">{{ flight.name }}</span>
        </li>
      {% endfor %}
    </ul>
    <div class="toggler is-flex">
      <button id="hide-flights" class="button">Hide all flights</button>
      <button id="show-flights" class="button">Show all flights</button>
    </div>
  </div>
</div>

{% include 'tipeee.part.html' %}
{% endblock %}


{% block footer_js %}
<script>
var map = L.map('map').setView([47.4771198,-0.5972396], 6);

let map_choice = {{ request.user.profile.maps }}
if(map_choice == 1) {
  // Topo
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
  }).addTo(map);
} else if(map_choice == 2) {
  // Imagery
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
  }).addTo(map);
} else {
  // Standard
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
}

// Draw all the flights
let polys = {}
let pictures = {}
pictures["None"] = []

let myHeaders = new Headers();
myHeaders.append("Accept", "application/json");

{% for flight in flights.all %}
  // Async load the flights
  fetch("{% url 'flights:detail' flight.pk %}", {headers: myHeaders})
    .then(response => response.json())
    .then(result => {
        polys["{{ flight.id }}"] = drawFlight(
          result.departure,
          result.arrival,
          result.waypoints,
          map,
          {{ request.user.profile.icons }},
          "hsl({% widthratio forloop.counter0 1 color_step %}, 100%, 50%)"
        )

        let flight = document.getElementById("flight-{{ flight.id }}")
        flight.classList.remove("loading")
        flight.classList.add("is-clickable")
    })
  pictures["{{ flight.id }}"] = []
{% endfor %}

// Event Listeners
document.querySelectorAll("ul.flight-list li .flight-name").forEach( el => {
  el.addEventListener("click", (event) => {
    map.fitBounds(polys[event.target.parentNode.dataset.flightid].polyline.getBounds())
  })
})


function showFlight(flightid, state) {
  if(state) {
    polys[flightid].polyline.addTo(map)
    if(polys[flightid].dep_mark) {
      polys[flightid].dep_mark.addTo(map)
      polys[flightid].arr_mark.addTo(map)
    }
    if(pictures[flightid].length) {
      pictures[flightid].forEach((item) => {
        item.marker.addTo(map)
      })
    }
  } else {
    polys[flightid].polyline.removeFrom(map)
    if(polys[flightid].dep_mark) {
      polys[flightid].dep_mark.removeFrom(map)
      polys[flightid].arr_mark.removeFrom(map)
    }
    if(pictures[flightid].length) {
      pictures[flightid].forEach((item) => {
        item.marker.removeFrom(map)
      })
    }
  }
}

document.querySelectorAll("ul.flight-list li .color-box").forEach( el => {
  el.addEventListener("click", (event) => {
    if(event.target.parentNode.classList.contains("loading"))
      return
    flightid = event.target.parentNode.dataset.flightid
    if(event.target.classList.contains("hide")) {
      event.target.classList.remove("hide")
      showFlight(flightid, true)
    } else {
      event.target.classList.add("hide")
      showFlight(flightid, false)
    }
  })
})

document.getElementById("hide-flights").addEventListener("click", (event) => {
  document.querySelectorAll("ul.flight-list li .color-box").forEach( el => {
    if(event.target.parentNode.classList.contains("loading"))
      return
    if(!el.classList.contains("hide" )) {
      flightid = el.parentNode.dataset.flightid
      el.classList.add("hide")
      showFlight(flightid, false)
    }
  })
})

document.getElementById("show-flights").addEventListener("click", (event) => {
  document.querySelectorAll("ul.flight-list li .color-box").forEach( el => {
    if(event.target.parentNode.classList.contains("loading"))
      return
    if(el.classList.contains("hide" )) {
      flightid = el.parentNode.dataset.flightid
      el.classList.remove("hide")
      showFlight(flightid, true)
    }
  })
})

// Draw pictures
let picture = undefined
{% for picture in pictures.all %}
picture = drawPicture([{{ picture.lat }}, {{ picture.lon }}], "{{ picture.name }}", "{{ picture.description }}", "{{ picture.data_file.url }}", map)
{% if picture.flight %}
pictures["{{ picture.flight.id }}"].push(picture)
{% else %}
pictures["None"].push(picture)
{% endif %}
{% endfor %}

document.getElementById("pictures-toggle").addEventListener('click', (event) => {
  if(event.target.checked) {
    for(let flight in pictures) {
      pictures[flight].forEach((item) => {
        item.marker.addTo(map)
      })
    }
  } else {
    for(let flight in pictures) {
      pictures[flight].forEach((item) => {
        item.marker.removeFrom(map)
      })
    }
  }
})

</script>
{% endblock %}

templates/messages.part.html
<!-- Messages from backend -->
{% if messages %}
<div class="messages-wrapper">
  {% for message in messages %}
  <div class="notification is-light
    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}is-info{% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}is-success{% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}is-warning{% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}is-danger{% endif %}
  ">
    <button class="delete"></button>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

templates/tipeee.part.html
{% load static %}

<img class="tipeee is-clickable modal-opener" data-target="tipeee-modal" src="{% static 'img/tipeee.png' %}">

<div class="modal" id="tipeee-modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Hi there!</p>
    </header>
    <section class="modal-card-body">
      <p class="mb-2">I'm Eskimon, a freelancer software engineer based in France.</p>
      <p class="mb-2">As I am passionnate by my job, when I am not working for a client I like to take on some fun ideas and challenges.</p>
      <p class="mb-2">Maybe some day I'll be able to do it full time, untill then I still need to pay bills and keep the server running to host your flights and pictures.</p>
      <p class="mb-2">So if you find this tool useful and want to help, you can sponsor me <a target="_blank" href="https://tipeee.com/eskimon" alt="My Tipeee">on Tipeeee</a></p>
      <p class="mb-2"></p>
      <p class="mb-2">Thanks for reading and have fun with this little tool!</p>
      <p class="mb-5"></p>
      <p class="mb-2 is-size-7">(And if you want to help, the code is here: <a href="https://github.com/Eskimon/fs-travelbook">github.com/Eskimon/fs-travelbook</a>)</p>
    </section>
  </div>
</div>